---
version: "3"

services:
  bot-maker-risks:
    build:
      context: .
    command: "main.py"
    environment:
      NODE_ENDPOINT:
      FALLBACK_NODE_ENDPOINT:
      EXPORTER_PORT:
      PARSE_INTERVAL:
      MAIN_ERROR_COOLDOWN:
      LOG_FORMAT: simple
      LOG_LEVEL: INFO
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.5.2
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:v2.47.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.24.0
    volumes:
      - ./alertmanager:/etc/alertmanager
    restart: unless-stopped

  discord_bot:
    image: lidofinance/alertmanager-discord:2.6.0
    volumes:
      - ./alertmanager-discord:/etc/alertmanager-discord
    restart: unless-stopped
    
volumes:
  prometheus-data:
