{
 "title": "Maker",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Maker wstETH(A) risks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(maker_risks_collateral_percentage{zone=~\"C|D|liquidation\", ilk=\"wstETH_A\"})"
    }
   ]
  },
  {
   "title": "Maker wstETH(B) risks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(maker_risks_collateral_percentage{zone=~\"C|D|liquidation\", ilk=\"wstETH_B\"})"
    }
   ]
  },
  {
   "title": "Maker steCRV(A) risks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(maker_risks_collateral_percentage{zone=~\"C|D|liquidation\", ilk=\"steCRV_A\"})"
    }
   ]
  },
  {
   "title": "Last updated at",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "maker_risks_processing_finished_seconds * 1000",
     "legendFormat": "{{ilk}}"
    }
   ]
  },
  {
   "title": "Last block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "maker_risks_eth_latest_block_num",
     "legendFormat": "{{ilk}}"
    }
   ]
  },
  {
   "title": "Maker wstETH(A) under risk % history",
   "type": "timeseries",
   "description": "Collateral is under risk in the case of collateral to loan ratio is below of 1.6",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(maker_risks_collateral_percentage{zone=~\"C|D|liquidation\", ilk=\"wstETH_A\"})",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Maker wstETH(B) under risk % history",
   "type": "timeseries",
   "description": "Collateral is under risk in the case of collateral to loan ratio is below of 1.6",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(maker_risks_collateral_percentage{zone=~\"C|D|liquidation\", ilk=\"wstETH_B\"})",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Maker steCRV(A) under risk % history",
   "type": "timeseries",
   "description": "Collateral is under risk in the case of collateral to loan ratio is below of 1.6",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(maker_risks_collateral_percentage{zone=~\"C|D|liquidation\", ilk=\"steCRV_A\"})",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "wstETH(A) zones overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{ilk=\"wstETH_A\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "wstETH(B) zones overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{ilk=\"wstETH_B\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "steCRV zones overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{ilk=\"steCRV_A\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "wstETH(A) in C %",
   "type": "timeseries",
   "description": "Percent of collateral within 1.1 .. 1.25 ratio range",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{zone=\"C\", ilk=\"wstETH_A\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "wstETH(B) in C %",
   "type": "timeseries",
   "description": "Percent of collateral within 1.1 .. 1.25 ratio range",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{zone=\"C\", ilk=\"wstETH_B\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "steCRV(A) in C %",
   "type": "timeseries",
   "description": "Percent of collateral within 1.1 .. 1.25 ratio range",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{zone=\"C\", ilk=\"steCRV_A\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "wstETH(A) in D %",
   "type": "timeseries",
   "description": "Percent of collateral within 1.0 .. 1.1 ratio range",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{zone=\"D\", ilk=\"wstETH_A\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "wstETH(B) in D %",
   "type": "timeseries",
   "description": "Percent of collateral within 1.0 .. 1.1 ratio range",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{zone=\"D\", ilk=\"wstETH_B\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "steCRV(A) in D %",
   "type": "timeseries",
   "description": "Percent of collateral within 1.0 .. 1.1 ratio range",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{zone=\"D\", ilk=\"steCRV_A\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  }
 ]
}