{
 "title": "Maker risks bot",
 "description": "https://www.notion.so/Maker-risks-bot-2b92291548734cbf95e13e2eaaaca516",
 "tags": [
  "bot",
  "automation",
  "apps"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "container", "query": "maker-risks-bot" },
   { "name": "service", "query": "maker-risks-bot" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(maker_risks_build_info, env)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(maker_risks_build_info{env=~\"$env\"}, source)"
    }
   },
   { "name": "search", "label": "Search query" }
  ]
 },
 "panels": [
  {
   "title": "Container uptime",
   "type": "stat",
   "description": "Bot container uptime",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"$container\",env=~\"$env\",source=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Fails count",
   "type": "stat",
   "description": "Count of fails inside the app modules",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(maker_risks_app_errors_total{env=~\"$env\",source=~\"$source\"}[$__range])",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Average fetch duration",
   "type": "stat",
   "description": "Average fetch duration by collateral type",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(maker_risks_fetch_duration{env=~\"$env\",source=~\"$source\"}[$__range])",
     "legendFormat": "{{ilk}}"
    }
   ]
  },
  {
   "title": "ETH RPC requests count",
   "type": "stat",
   "description": "Count of requests to ETH RPC node ",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(maker_risks_eth_rpc_requests_total{env=~\"$env\",source=~\"$source\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP requests count",
   "type": "stat",
   "description": "Count of HTTP requests to external services ",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(maker_risks_http_requests_total{env=~\"$env\",source=~\"$source\"}[$__range]))"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "RPC requests duration",
   "type": "heatmap",
   "description": "Duration of requests to the RPC provider",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(maker_risks_eth_rpc_requests_duration_bucket{env=~\"$env\",source=~\"$source\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RPC requests errors",
   "type": "timeseries",
   "description": "Number of request errors to the RPC provider",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(maker_risks_eth_rpc_requests_total{code!=\"0\",env=~\"$env\",source=~\"$source\"}[1m])) by (code)",
     "legendFormat": "code={{code}}"
    }
   ]
  },
  {
   "title": "HTTP requests duration",
   "type": "heatmap",
   "description": "Duration of requests to external HTTP services",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(maker_risks_http_requests_duration_bucket{env=~\"$env\",source=~\"$source\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP requests errors",
   "type": "timeseries",
   "description": "Number of request errors to external HTTP services",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(maker_risks_http_requests_total{http_code!~\"[1-3][0-9][0-9]\",env=~\"$env\",source=~\"$source\"}[1m])) by (http_code)",
     "legendFormat": "{{http_code}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{container_name=\"$container\",env=~\"$env\",source=~\"$source\"} | json | line_format \"[{{.levelname}}] {{.message}}\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Error logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "{container_name=\"$container\",env=~\"$env\",source=~\"$source\"} | json |= \"ERROR\" | line_format \"[{{.levelname}}] {{.message}}\" |~ \"$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Resources usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Cumulative cpu time consumed",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(irate(container_cpu_user_seconds_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100) + (sum(irate(container_cpu_system_seconds_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100)",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{env=~\"$env\",source=~\"$source\",name=~\"$container\"}) by (name)",
       "legendFormat": "mem"
      }
     ]
    },
    {
     "title": "Opened FDs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_file_descriptors{env=~\"$env\",source=~\"$source\",name=~\"$container\"}",
       "legendFormat": "FDs"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)) + (sum(irate(container_network_transmit_bytes_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name))",
       "legendFormat": "net"
      }
     ]
    }
   ]
  },
  {
   "title": "Python stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python GC uncollectable",
     "type": "timeseries",
     "description": "Uncollectable objects count found during GC",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "increase(python_gc_objects_uncollectable_total{service=\"$service\",env=~\"$env\",source=~\"$source\"}[$__rate_interval])",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    },
    {
     "title": "Python GC collected",
     "type": "timeseries",
     "description": "Objects collected during GC",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "increase(python_gc_objects_collected_total{service=\"$service\",env=~\"$env\",source=~\"$source\"}[$__rate_interval])",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    },
    {
     "title": "Python GC collections",
     "type": "timeseries",
     "description": "Number of times this generation was collected",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "increase(python_gc_collections_total{service=\"$service\",env=~\"$env\",source=~\"$source\"}[$__rate_interval])",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    },
    {
     "title": "Process file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "process_open_fds{service=\"$service\",env=~\"$env\",source=~\"$source\"}",
       "legendFormat": "Open FD"
      },
      {
       "expr": "process_max_fds{service=\"$service\",env=~\"$env\",source=~\"$source\"}",
       "legendFormat": "Max FD"
      }
     ]
    },
    {
     "title": "Process resident memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{service=\"$service\",env=~\"$env\",source=~\"$source\"}"
      }
     ]
    },
    {
     "title": "Process virtual memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{service=\"$service\",env=~\"$env\",source=~\"$source\"}"
      }
     ]
    }
   ]
  }
 ]
}