{
 "title": "Maker",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Maker wstETH risks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(maker_risks_collateral_percentage{zone=~\"C|D|liquidation\"})"
    }
   ]
  },
  {
   "title": "Maker wstETH under risk % history",
   "type": "timeseries",
   "description": "Collateral is under risk in the case of collateral to loan ratio is below of 1.6",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(maker_risks_collateral_percentage{zone=~\"C|D|liquidation\"})",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "wstETH in C %",
   "type": "timeseries",
   "description": "Percent of collateral within 1.1 .. 1.25 ratio range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{zone=\"C\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "wstETH in D %",
   "type": "timeseries",
   "description": "Percent of collateral within 1.0 .. 1.1 ratio range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage{zone=\"D\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "wstETH zones overview",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "maker_risks_collateral_percentage",
     "legendFormat": "{{zone}}"
    }
   ]
  }
 ]
}