---
name: Prepare release draft

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  prepare-release-draft:
    uses: lidofinance/actions/.github/workflows/prepare-release-draft.yml@main
    with:
      target: master
